---
Outputs:
  AdminRoleArn:
    Value: !GetAtt AdminRole.Arn
  AdminRoleUrl:
    Value: !Sub
      - "https://signin.aws.amazon.com/switchrole?roleName=${RoleName}&account=${AccountId}"
      - RoleName: !Ref AdminRole
        AccountId: !Ref AWS::AccountId

Parameters:
  Users:
    Type: String

Resources:
  AdminGroup:
    Type: AWS::IAM::Group

  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              AWS:
                - !Sub
                  - "arn:aws:iam::${AccountId}:user/${User}"
                  - AccountId: !Ref AWS::AccountId
                    User: !Select [0, !Split [",", !Ref Users]]
                - !Sub
                  - "arn:aws:iam::${AccountId}:user/${User}"
                  - AccountId: !Ref AWS::AccountId
                    User: !Select [1, !Split [",", !Ref Users]]
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  AssumeAdminRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref AdminGroup
      PolicyName: assume-admin-role-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !GetAtt AdminRole.Arn
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
